histogram
js-tasks-ru/htmlcss-20211125_postbox404 pull request #12
Opened 2021-12-11 12:18 UTC by Dmitry1517

2021-12-11 12:18 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-12-11 13:19 UTC, GSemikozov requested changes

2021-12-11 13:19 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    width: 354px;
ширину и высоту лучше не фиксировать, чтобы блок был адаптивным

2021-12-11 13:19 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    margin-top: 16px;
чтобы не задавать марджины на уровне дочерних элементов, лучше один раз указать общие паддинги на уровне .histogram

2021-12-11 13:19 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    width: 9px;
лучше flex-basis)

2021-12-12 17:56 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-12-13 02:53 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-12-13 02:53 UTC, Dmitry1517 commented on 04-lection2/01-histogram/histogram.css
> +    width: 354px;
Исправил

2021-12-13 02:53 UTC, Dmitry1517 commented on 04-lection2/01-histogram/histogram.css
> +    margin-top: 16px;
Исправил

2021-12-13 02:53 UTC, Dmitry1517 commented on 04-lection2/01-histogram/histogram.css
> +    width: 9px;
Исправил

2021-12-16 09:45 UTC, GSemikozov approved these changes

2021-12-16 09:45 UTC, merged