checkbox
js-tasks-ru/htmlcss-20211125_postbox404 pull request #16
Opened 2021-12-23 07:49 UTC by Dmitry1517

2021-12-23 07:50 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-12-23 19:50 UTC, GSemikozov requested changes

2021-12-23 19:50 UTC, GSemikozov commented on 07-lection5/01-checkbox/checkbox.css
> +.checkbox__state_disabled {
выглядит как лишний модификатор

2021-12-24 15:47 UTC, Dmitry1517 commented on 07-lection5/01-checkbox/checkbox.css
> +.checkbox__state_disabled {
Исправил

2021-12-24 15:47 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-12-24 18:49 UTC, GSemikozov approved these changes

2021-12-24 18:50 UTC, merged