avatar
js-tasks-ru/htmlcss-20211125_postbox404 pull request #20
Opened 2022-01-08 10:35 UTC by Dmitry1517

2022-01-08 10:35 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-01-18 20:05 UTC, GSemikozov requested changes

2022-01-18 20:05 UTC, GSemikozov commented on 06-lection4/01-avatar/avatar.css
> +    width: 100%;
тот случай когда лучше фиксированные значения задать как в макете)

2022-01-21 20:02 UTC, GSemikozov approved these changes

2022-01-21 20:02 UTC, jsru commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2022-01-22 04:39 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-01-23 04:16 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-01-23 12:55 UTC, GSemikozov approved these changes

2022-01-23 12:55 UTC, merged