burger
js-tasks-ru/htmlcss-20211125_postbox404 pull request #23
Opened 2022-01-15 05:39 UTC by Dmitry1517

2022-01-15 05:40 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-01-19 14:53 UTC, GSemikozov requested changes

2022-01-19 14:53 UTC, GSemikozov commented on 09-lection7/01-burger-menu/burger-menu.css
> +    left: -100%;
меню лучше двигать изменяя translateX а не left - обсуждали на лекции)

2022-01-19 14:53 UTC, GSemikozov commented on 09-lection7/01-burger-menu/burger-menu.css
> +    left: -100%;
но вообще - должен двигаться весь блок .burger, кнопка-триггер для открытия меню будет внешней и никак не привязана к меню.
хотя - это реализация без js?

2022-01-21 20:02 UTC, GSemikozov approved these changes

2022-01-21 20:02 UTC, merged