project-1
js-tasks-ru/htmlcss-20211125_postbox404 pull request #26
Opened 2022-02-02 06:09 UTC by Dmitry1517

2022-02-02 06:09 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-02-02 22:23 UTC, GSemikozov requested changes

2022-02-02 22:23 UTC, GSemikozov commented on components/card/card.css
> +.avatar_component-preview {
тут и ниже - в компонента Карточка слишком много сторонних классов, просьба свериться и заверстать по БЭМ)

2022-02-04 03:53 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-02-04 12:46 UTC, GSemikozov requested changes

2022-02-04 12:46 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.modal__mindow_preview {
здесь и ниже - чтобы не задавать каждому элементу свой класс-модификатор, достаточно задать общий модификатор на уровне блока, а дальше - так: .modal_preview .modal__title { специфические стили }

2022-02-04 12:46 UTC, GSemikozov commented on components/card/card.css
> +.card__footer_tooltip {
с футером надо иначе - под каждый компонент создавать свой модификатор это не вариант. Пусть футер будет всегда прибит к низу карточки, а секция превью (куда встраиваем компоненты) пусть растягивается в зависимости от внутреннего содержимого

2022-02-07 08:42 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-02-07 19:54 UTC, GSemikozov approved these changes

2022-02-07 19:54 UTC, merged