project-2
js-tasks-ru/htmlcss-20211125_postbox404 pull request #27
Opened 2022-02-14 12:01 UTC by Dmitry1517

2022-02-14 12:02 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-02-16 09:33 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-02-16 21:25 UTC, GSemikozov requested changes

2022-02-16 21:25 UTC, GSemikozov commented on components/tabs/tabs.css
> +.tabs > input[type="radio"] {
у инпута должен быть класс который будет обозначать что это элемент компонента Табс - .tabs__input )

2022-02-16 21:25 UTC, GSemikozov commented on components/tabs/tabs.css
> +.tab-btn-1:checked ~ .content-1,
.tabs__input_1 и тд

2022-02-17 09:50 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-02-17 15:04 UTC, Dmitry1517 commented on components/tabs/tabs.css
> +.tabs > input[type="radio"] {
+

2022-02-17 15:05 UTC, Dmitry1517 commented on components/tabs/tabs.css
> +.tab-btn-1:checked ~ .content-1,
Исправил

2022-02-17 15:05 UTC, Dmitry1517 commented on components/tabs/tabs.css
> +.tabs > input[type="radio"] {
Исправил

2022-02-18 10:59 UTC, GSemikozov approved these changes

2022-02-18 10:59 UTC, merged